import Head from 'next/head';
import Banner from '../components/Banner';
import Nav from '../components/Nav';
import Row from '../components/Row';
import requests from '../requests';

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Banner />
      <Row
        title="Neflix Originals"
        fetchUrls={requests.fetchNetflixOriginals}
        isLargeRow={true}
      />
      <Row title="Trending Now" fetchUrls={requests.fetchTrending} />
      <Row title="Top Rated" fetchUrls={requests.fetchTopRated} />
      <Row title="Action movies" fetchUrls={requests.fetchActionMovies} />
      <Row title="Comedy Movies" fetchUrls={requests.fetchComedyMovies} />
      <Row title="Horror Movies" fetchUrls={requests.fetchHorrorMovies} />
      <Row title="Romance Movies" fetchUrls={requests.fetchRomanceMovies} />
      <Row title="Documentaries" fetchUrls={requests.fetchDocumentaries} />
    </div>
  );
}
